# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
warnings_are_errors: true
sudo: false
cache: packages
bioc_required: true

bioc_packages:
  - xcms
  - CAMERA
  - msdata
  - mtbls2
  - BiocGenerics
